# Generated by Django 6.0.6 on 2026-06-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloudinary_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
