# Generated by Django 6.0.6 on 2026-06-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0003_document_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
